SET foreign_key_checks = 0;
DROP TABLE Account;
DROP TABLE Customers_Have_1;
DROP TABLE Customers_Have_2;
DROP TABLE Sellers;
DROP TABLE Products_Post;
DROP TABLE Purchase;
DROP TABLE Coupon;
DROP TABLE Warehouse;
DROP TABLE Uses;
DROP TABLE Store;
DROP TABLE Transfer_Station;
DROP TABLE Transfer_To;
DROP TABLE Ship_To;
DROP TABLE Delivery;
DROP TABLE Staff_2;
DROP TABLE Staff_1;
DROP TABLE Logistic_Staff;
DROP TABLE Customer_Service;
DROP TABLE Work_On;
DROP TABLE Help;
SET foreign_key_checks = 1;
